package app.rolla.bluetoothSdk.connect

enum class Operation {
    CONNECT,
    DISCONNECT,
    DISCONNECT_ALL,
    SERVICE_DISCOVERY,
    READ_CHARACTERISTIC,
    NOTIFY_CHARACTERISTIC,
    WRITE_CHARACTERISTIC,
    DESCRIPTOR_WRITE,
    SUBSCRIBE_CHARACTERISTIC,
    UNSUBSCRIBE_CHARACTERISTIC,
    UNKNOWN
}